### PR TITLE
Snoble/fix recurrsion ne bug

### PR DESCRIPTION
**Pull request by snoble**
I was wrapping the `in` with a `Recursion` expression when what I wanted was to wrap the `arg` and then add the `arg` to the `in`'s environment

### CODE REVIEW

**Comment by snoble** [comment]
The failing test seems to be due to a failed wget by bazel
`Error downloading [http://central.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar`
https://travis-ci.org/github/johnynek/bosatsu/jobs/673923393#L1277

**Comment by johnynek** [comment]
huh, maybe we need to use https now to download?

**Comment by snoble** [comment]
Ah, url deprecation. I'll make a separate PR for the fix. https://central.sonatype.org/articles/2019/Jul/15/central-http-deprecation-update/

**Comment by johnynek** [comment]
if #474 goes green, I'll merge that, and you can merge master and your PR should be green.

**Comment by snoble** [comment]
Green now!

**Pull request merged**
